# -*- coding: utf-8 -*-
"""DAY@3TASK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKyXXxt8ubPQhOop0XeBOwCshWwn2rrq
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

#perameters
vocab_size=1000
embedding_dim=64
max_length=100

from ast import mod
#build the model
model=Sequential([
    Embedding(input_dim=vocab_size,output_dim=embedding_dim, input_length=max_length),
    LSTM(64),
    Dense(1, activation='sigmoid')
])

#compile the model
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'])

#print model summary
model.summary()